Updated to support Stalwart Mail server
GermanCoding/Roundcube_TLS_Icon pull request #22
Opened 2024-09-16 19:40 UTC by dehoej

The necessary regex to support Stalwart mail server (https://stalw.art) has been added.

2024-09-16 19:55 UTC, williamdes approved these changes
Thank you!
I am testing it

2024-09-17 15:26 UTC, GermanCoding requested changes
Hi, thanks for your contribution!

* We have unit tests for all regexes here: https://github.com/GermanCoding/Roundcube_TLS_Icon/blob/master/test/TlsIconTest.php. For new regexes, please add new test cases with example Stalwart Received-Headers - including edge cases, if possible. This allows us to both test the code and also have a nice way of understanding the regex. Currently I don't see why the existing Postfix regex doesn't work, so having an example is always great.
* We should also update the README if a new regex is added, but I can do that if necessary.

2024-09-17 15:26 UTC, GermanCoding commented on tls_icon.php
> +    const STALWART_TLS_REGEX = "/\(using (TLSv1\.[23] with cipher .+)\) by .+ \(Stalwart SMTP\)/im";
This regex appears similar to the Postfix regex. Is there a specific reason why the existing Postfix regex doesn't work for Stalwart?

2024-09-17 15:28 UTC, GermanCoding commented on tls_icon.php
> +    const STALWART_TLS_REGEX = "/\(using (TLSv1\.[23] with cipher .+)\) by .+ \(Stalwart SMTP\)/im";
Also, I don't like having overly specific regexes. Currently TLSv1.2 and TLSv1.3 are the only protocol versions commonly used, but to anticipate a future TLSv1.3 or TLSv2.0 I don't think the regex needs to match only  `TLSv1\.[23]`.

2024-09-18 21:54 UTC, williamdes commented on tls_icon.php
> +    const STALWART_TLS_REGEX = "/\(using (TLSv1\.[23] with cipher .+)\) by .+ \(Stalwart SMTP\)/im";
For reference the name seems to be hard coded: https://github.com/stalwartlabs/mail-server/blob/24df9a0352a948f67ad58ab0d7d7423002863d43/crates/smtp/src/inbound/data.rs#L947

But I do not see the point of keeping it in the regex
```suggestion
    const STALWART_TLS_REGEX = "/\(using (TLSv1\.[23] with cipher .+)\)/im";
```

2025-06-17 18:25 UTC, GermanCoding commented
Stalwart should be supported as of release 1.4.0, please let me know if there are any issues with Stalwart support.

2025-06-17 18:25 UTC, closed without merging